name: heben
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  demoji: ^1.0.1
  google_fonts: ^0.3.9
  overlay_support: ^1.0.2
  eva_icons_flutter: ^2.0.0
  flutter_tags: ^0.4.7
  pull_to_refresh: ^1.5.8
  flutter_spinkit: ^4.1.2
  vibrate: ^0.0.4
  video_player: ^0.10.8+1
  highlight_text: ^0.7.2
  auto_size_text: ^2.1.0
  getflutter: ^1.0.11
  flutter_statusbarcolor: ^0.2.3
  photo_manager: 0.5.0
  faker: ^1.2.1
  carousel_slider: 1.4.1
  photo_view: ^0.9.2
  flutter_ijkplayer: ^0.3.5+1
  permission_handler: ^3.2.0
  flutter_rtmp: ^0.1.4
  argon_buttons_flutter: ^1.0.2
  like_button: ^0.2.0
  cloud_firestore: 0.13.4
  firebase_auth: 0.15.3
  firebase_storage: ^3.1.3
  firebase_messaging: ^6.0.13
  firebase_analytics: ^5.0.11
  flutter_image_compress: ^0.6.5+1
  flutter_video_compress: ^0.3.7+8
  path_provider: ^1.6.5
  email_validator: ^1.0.4
  loading_overlay: ^0.2.1
  platform_alert_dialog: ^1.0.0+2
  image_picker: ^0.6.5
  image_cropper: ^1.2.1
  uuid: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
